"""add idempotency_key to payments table

Revision ID: 20260226_0008
Revises: 20260214_0007
Create Date: 2026-02-26 00:00:00

Adds an optional idempotency_key column to the payments table plus a
composite unique constraint on (order_id, idempotency_key).

Rationale
---------
The ``POST /payments/razorpay/initiate/{order_id}`` endpoint originally had
no protection against double-submission.  A client that retried a network
timeout would create two separate Razorpay orders for the same campus order,
leading to double-charge risk.

With this migration the endpoint accepts an ``X-Idempotency-Key`` header
(a per-attempt UUID generated by the frontend).  If a row with
(order_id, idempotency_key) already exists, the service returns that row
immediately without calling Razorpay again.  The unique constraint is the
database-level safety net that prevents a race condition between two
concurrent requests arriving with the same key.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20260226_0008"
down_revision = "20260214_0007"
branch_labels = None
depends_on = None


def _column_exists(table: str, column: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(c["name"] == column for c in inspector.get_columns(table))


def _constraint_exists(table: str, constraint: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    # unique_constraints may not be populated on SQLite; ignore gracefully
    try:
        names = {uc["name"] for uc in inspector.get_unique_constraints(table)}
        return constraint in names
    except Exception:
        return False


def upgrade() -> None:
    if not _column_exists("payments", "idempotency_key"):
        op.add_column(
            "payments",
            sa.Column("idempotency_key", sa.String(), nullable=True),
        )

    # Add index for fast look-ups (order_id, idempotency_key)
    # SQLite silently ignores duplicate index creation; PostgreSQL requires
    # the IF NOT EXISTS guard via raw SQL or a try/except.
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        # SQLite: create index if not exists
        bind.execute(
            sa.text(
                "CREATE INDEX IF NOT EXISTS ix_payments_idempotency_key "
                "ON payments (idempotency_key)"
            )
        )
        bind.execute(
            sa.text(
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_order_idempotency "
                "ON payments (order_id, idempotency_key) "
                "WHERE idempotency_key IS NOT NULL"
            )
        )
    else:
        # PostgreSQL / other dialects
        if not _constraint_exists("payments", "uq_payment_order_idempotency"):
            op.create_index(
                "ix_payments_idempotency_key",
                "payments",
                ["idempotency_key"],
                unique=False,
                if_not_exists=True,
            )
            op.create_unique_constraint(
                "uq_payment_order_idempotency",
                "payments",
                ["order_id", "idempotency_key"],
            )


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        bind.execute(sa.text("DROP INDEX IF EXISTS uq_payment_order_idempotency"))
        bind.execute(sa.text("DROP INDEX IF EXISTS ix_payments_idempotency_key"))
    else:
        try:
            op.drop_constraint(
                "uq_payment_order_idempotency", "payments", type_="unique"
            )
        except Exception:
            pass
        try:
            op.drop_index("ix_payments_idempotency_key", table_name="payments")
        except Exception:
            pass

    if _column_exists("payments", "idempotency_key"):
        op.drop_column("payments", "idempotency_key")
